// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiV1FilesByTrackIdData, DeleteApiV1FilesByTrackIdErrors, DeleteApiV1FilesByTrackIdResponses, GetApiV1AuthStatusData, GetApiV1AuthStatusResponses, GetApiV1FilesData, GetApiV1FilesErrors, GetApiV1FilesResponses, GetApiV1InviteByInviteCodeData, GetApiV1InviteByInviteCodeErrors, GetApiV1InviteByInviteCodeResponses, GetApiV1JoinTokenData, GetApiV1JoinTokenErrors, GetApiV1JoinTokenResponses, GetApiV1StreamByPathData, GetApiV1StreamByPathErrors, GetApiV1StreamByPathResponses, GetApiV1TablesData, GetApiV1TablesErrors, GetApiV1TablesResponses, GetApiV1TrackTypesData, GetApiV1TrackTypesErrors, GetApiV1TrackTypesResponses, GetApiV1WsData, GetApiV1WsErrors, PostApiV1AuthLogoutData, PostApiV1AuthLogoutResponses, PostApiV1FilesData, PostApiV1FilesErrors, PostApiV1FilesResponses, PostApiV1LoginData, PostApiV1LoginErrors, PostApiV1LoginResponses, PutApiV1FilesByTrackIdData, PutApiV1FilesByTrackIdErrors, PutApiV1FilesByTrackIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Authenticate user
 */
export const postApiV1Login = <ThrowOnError extends boolean = false>(options: Options<PostApiV1LoginData, ThrowOnError>) => (options.client ?? client).post<PostApiV1LoginResponses, PostApiV1LoginErrors, ThrowOnError>({
    url: '/api/v1/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get current authentication status
 */
export const getApiV1AuthStatus = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1AuthStatusData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1AuthStatusResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'auth_token',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/status',
    ...options
});

/**
 * Logout current user
 */
export const postApiV1AuthLogout = <ThrowOnError extends boolean = false>(options?: Options<PostApiV1AuthLogoutData, ThrowOnError>) => (options?.client ?? client).post<PostApiV1AuthLogoutResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'auth_token',
            type: 'apiKey'
        }],
    url: '/api/v1/auth/logout',
    ...options
});

/**
 * List all audio tracks
 */
export const getApiV1Files = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1FilesData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1FilesResponses, GetApiV1FilesErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'auth_token',
            type: 'apiKey'
        }],
    url: '/api/v1/files',
    ...options
});

/**
 * Upload new audio track
 */
export const postApiV1Files = <ThrowOnError extends boolean = false>(options: Options<PostApiV1FilesData, ThrowOnError>) => (options.client ?? client).post<PostApiV1FilesResponses, PostApiV1FilesErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{
            in: 'cookie',
            name: 'auth_token',
            type: 'apiKey'
        }],
    url: '/api/v1/files',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Delete an audio track
 */
export const deleteApiV1FilesByTrackId = <ThrowOnError extends boolean = false>(options: Options<DeleteApiV1FilesByTrackIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiV1FilesByTrackIdResponses, DeleteApiV1FilesByTrackIdErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'auth_token',
            type: 'apiKey'
        }],
    url: '/api/v1/files/{trackID}',
    ...options
});

/**
 * Update audio track information
 */
export const putApiV1FilesByTrackId = <ThrowOnError extends boolean = false>(options: Options<PutApiV1FilesByTrackIdData, ThrowOnError>) => (options.client ?? client).put<PutApiV1FilesByTrackIdResponses, PutApiV1FilesByTrackIdErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'auth_token',
            type: 'apiKey'
        }],
    url: '/api/v1/files/{trackID}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get a new join token for players
 */
export const getApiV1JoinToken = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1JoinTokenData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1JoinTokenResponses, GetApiV1JoinTokenErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'auth_token',
            type: 'apiKey'
        }],
    url: '/api/v1/joinToken',
    ...options
});

/**
 * Stream audio content
 */
export const getApiV1StreamByPath = <ThrowOnError extends boolean = false>(options: Options<GetApiV1StreamByPathData, ThrowOnError>) => (options.client ?? client).get<GetApiV1StreamByPathResponses, GetApiV1StreamByPathErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'auth_token',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/api/v1/stream/{path}',
    ...options
});

/**
 * Get table details by invite code (public endpoint)
 */
export const getApiV1InviteByInviteCode = <ThrowOnError extends boolean = false>(options: Options<GetApiV1InviteByInviteCodeData, ThrowOnError>) => (options.client ?? client).get<GetApiV1InviteByInviteCodeResponses, GetApiV1InviteByInviteCodeErrors, ThrowOnError>({ url: '/api/v1/invite/{inviteCode}', ...options });

/**
 * Get list of tables
 */
export const getApiV1Tables = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1TablesData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1TablesResponses, GetApiV1TablesErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'auth_token',
            type: 'apiKey'
        }],
    url: '/api/v1/tables',
    ...options
});

/**
 * Get available track types
 */
export const getApiV1TrackTypes = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1TrackTypesData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1TrackTypesResponses, GetApiV1TrackTypesErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'auth_token',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/api/v1/trackTypes',
    ...options
});

/**
 * WebSocket connection for real-time updates
 */
export const getApiV1Ws = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1WsData, ThrowOnError>) => (options?.client ?? client).get<unknown, GetApiV1WsErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'auth_token',
            type: 'apiKey'
        }, {
            in: 'query',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/api/v1/ws',
    ...options
});
