// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type LoginRequest = {
    username: string;
    password: string;
};

export type LoginResponse = {
    success: boolean;
    error: string;
};

export type JoinRequest = {
    token: string;
};

export type JoinTokenResponse = {
    token: string;
};

export type AuthStatusResponse = {
    authenticated: boolean;
    role: 'gm' | 'player';
};

export type Track = {
    id: string;
    createdAt: string;
    name: string;
    path: string;
    typeID: string;
};

export type UpdateTrackRequest = {
    id: string;
    name?: string;
    typeID?: string;
};

export type TrackType = {
    id: string;
    name: string;
    color: string;
    isRepeating: boolean;
    allowSimultaneousPlay: boolean;
};

export type Table = {
    id: string;
    name: string;
    inviteCode: string;
    createdAt: string;
};

export type InviteDetails = {
    tableName: string;
    tableID: string;
};

export type AssignTracksRequest = {
    /**
     * Array of track IDs to assign to the table
     */
    tracks: Array<string>;
};

export type PostApiV1LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/login';
};

export type PostApiV1LoginErrors = {
    /**
     * Invalid credentials
     */
    401: LoginResponse;
};

export type PostApiV1LoginError = PostApiV1LoginErrors[keyof PostApiV1LoginErrors];

export type PostApiV1LoginResponses = {
    /**
     * Login successful
     */
    200: LoginResponse;
};

export type PostApiV1LoginResponse = PostApiV1LoginResponses[keyof PostApiV1LoginResponses];

export type GetApiV1AuthStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/status';
};

export type GetApiV1AuthStatusResponses = {
    /**
     * Authentication status
     */
    200: AuthStatusResponse;
};

export type GetApiV1AuthStatusResponse = GetApiV1AuthStatusResponses[keyof GetApiV1AuthStatusResponses];

export type PostApiV1AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type PostApiV1AuthLogoutResponses = {
    /**
     * Logout successful
     */
    200: unknown;
};

export type GetApiV1FilesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/files';
};

export type GetApiV1FilesErrors = {
    /**
     * Not authorized
     */
    403: unknown;
};

export type GetApiV1FilesResponses = {
    /**
     * List of tracks
     */
    200: Array<Track>;
};

export type GetApiV1FilesResponse = GetApiV1FilesResponses[keyof GetApiV1FilesResponses];

export type PostApiV1FilesData = {
    body: {
        files?: Blob | File;
        name?: string;
        typeID?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/files';
};

export type PostApiV1FilesErrors = {
    /**
     * Not authorized
     */
    403: unknown;
};

export type PostApiV1FilesResponses = {
    /**
     * File uploaded successfully
     */
    200: Track;
};

export type PostApiV1FilesResponse = PostApiV1FilesResponses[keyof PostApiV1FilesResponses];

export type DeleteApiV1FilesByTrackIdData = {
    body?: never;
    path: {
        trackID: string;
    };
    query?: never;
    url: '/api/v1/files/{trackID}';
};

export type DeleteApiV1FilesByTrackIdErrors = {
    /**
     * Not authorized
     */
    403: unknown;
    /**
     * Track not found
     */
    404: unknown;
};

export type DeleteApiV1FilesByTrackIdResponses = {
    /**
     * Track deleted successfully
     */
    200: unknown;
};

export type PutApiV1FilesByTrackIdData = {
    body: UpdateTrackRequest;
    path: {
        trackID: string;
    };
    query?: never;
    url: '/api/v1/files/{trackID}';
};

export type PutApiV1FilesByTrackIdErrors = {
    /**
     * Invalid request body
     */
    400: unknown;
    /**
     * Not authorized
     */
    403: unknown;
    /**
     * Track not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type PutApiV1FilesByTrackIdResponses = {
    /**
     * Track updated successfully
     */
    200: Track;
};

export type PutApiV1FilesByTrackIdResponse = PutApiV1FilesByTrackIdResponses[keyof PutApiV1FilesByTrackIdResponses];

export type GetApiV1JoinTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/joinToken';
};

export type GetApiV1JoinTokenErrors = {
    /**
     * Not authorized
     */
    403: unknown;
};

export type GetApiV1JoinTokenResponses = {
    /**
     * Join token
     */
    200: JoinTokenResponse;
};

export type GetApiV1JoinTokenResponse = GetApiV1JoinTokenResponses[keyof GetApiV1JoinTokenResponses];

export type GetApiV1StreamByPathData = {
    body?: never;
    path: {
        path: string;
    };
    query?: never;
    url: '/api/v1/stream/{path}';
};

export type GetApiV1StreamByPathErrors = {
    /**
     * Not authorized
     */
    403: unknown;
    /**
     * File not found
     */
    404: unknown;
};

export type GetApiV1StreamByPathResponses = {
    /**
     * Audio stream
     */
    200: string;
};

export type GetApiV1StreamByPathResponse = GetApiV1StreamByPathResponses[keyof GetApiV1StreamByPathResponses];

export type GetApiV1InviteByInviteCodeData = {
    body?: never;
    path: {
        /**
         * The invite code for the table
         */
        inviteCode: string;
    };
    query?: never;
    url: '/api/v1/invite/{inviteCode}';
};

export type GetApiV1InviteByInviteCodeErrors = {
    /**
     * Missing or invalid invite code
     */
    400: unknown;
    /**
     * Table not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetApiV1InviteByInviteCodeResponses = {
    /**
     * Table details for the invite code
     */
    200: InviteDetails;
};

export type GetApiV1InviteByInviteCodeResponse = GetApiV1InviteByInviteCodeResponses[keyof GetApiV1InviteByInviteCodeResponses];

export type GetApiV1TablesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tables';
};

export type GetApiV1TablesErrors = {
    /**
     * Not authorized
     */
    403: unknown;
};

export type GetApiV1TablesResponses = {
    /**
     * List of tables
     */
    200: Array<Table>;
};

export type GetApiV1TablesResponse = GetApiV1TablesResponses[keyof GetApiV1TablesResponses];

export type GetApiV1TablesByTableIdTracksData = {
    body?: never;
    path: {
        /**
         * The UUID of the table
         */
        tableID: string;
    };
    query?: never;
    url: '/api/v1/tables/{tableID}/tracks';
};

export type GetApiV1TablesByTableIdTracksErrors = {
    /**
     * Invalid table ID
     */
    400: unknown;
    /**
     * Not authorized (GM role required)
     */
    403: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetApiV1TablesByTableIdTracksResponses = {
    /**
     * List of tracks for the table
     */
    200: Array<Track>;
};

export type GetApiV1TablesByTableIdTracksResponse = GetApiV1TablesByTableIdTracksResponses[keyof GetApiV1TablesByTableIdTracksResponses];

export type PostApiV1TablesByTableIdTracksData = {
    body: AssignTracksRequest;
    path: {
        /**
         * The UUID of the table
         */
        tableID: string;
    };
    query?: never;
    url: '/api/v1/tables/{tableID}/tracks';
};

export type PostApiV1TablesByTableIdTracksErrors = {
    /**
     * Invalid table ID or request body
     */
    400: unknown;
    /**
     * Not authorized (GM role required)
     */
    403: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type PostApiV1TablesByTableIdTracksResponses = {
    /**
     * Tracks successfully assigned to table
     */
    200: unknown;
};

export type GetApiV1TrackTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/trackTypes';
};

export type GetApiV1TrackTypesErrors = {
    /**
     * Not authorized
     */
    403: unknown;
};

export type GetApiV1TrackTypesResponses = {
    /**
     * List of track types
     */
    200: Array<TrackType>;
};

export type GetApiV1TrackTypesResponse = GetApiV1TrackTypesResponses[keyof GetApiV1TrackTypesResponses];

export type GetApiV1WsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ws';
};

export type GetApiV1WsErrors = {
    /**
     * Not authorized
     */
    403: unknown;
};
