services:
  skald:
    image: ghcr.io/terrabitz/rpg-audio-streamer
    container_name: skald
    restart: unless-stopped
    env_file: ../.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - app_data:/app/data
      - caddy_data:/caddy/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  app_data:
  caddy_data:
