services:
  skald:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: skald
    restart: unless-stopped
    env_file: ../.env
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - app_data:/app/data
      - caddy_data:/caddy/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  app_data:
  caddy_data: