// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlitedb

type Track struct {
	ID        []byte
	CreatedAt string
	Name      string
	Path      string
	TypeID    []byte
}

type TrackType struct {
	ID                    []byte
	Name                  string
	Color                 string
	IsRepeating           bool
	AllowSimultaneousPlay bool
	CreatedAt             string
}
