// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlitedb

import (
	"database/sql"
)

type Track struct {
	ID        []byte
	CreatedAt sql.NullString
	Name      string
	Path      string
	Type      string
}
