// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlitedb

type Track struct {
	ID        []byte
	CreatedAt string
	Name      string
	Path      string
	Type      string
}
