// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tables.sql

package sqlitedb

import (
	"context"
)

const getTableByInviteCode = `-- name: GetTableByInviteCode :one
SELECT id, name, invite_code, created_at FROM tables WHERE invite_code = ?1
`

func (q *Queries) GetTableByInviteCode(ctx context.Context, inviteCode string) (Table, error) {
	row := q.db.QueryRowContext(ctx, getTableByInviteCode, inviteCode)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InviteCode,
		&i.CreatedAt,
	)
	return i, err
}

const getTables = `-- name: GetTables :many
SELECT id, name, invite_code, created_at FROM tables ORDER BY created_at DESC
`

func (q *Queries) GetTables(ctx context.Context) ([]Table, error) {
	rows, err := q.db.QueryContext(ctx, getTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Table
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InviteCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
