name: Test Go

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          ffmpeg

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...
