name: Test Docker

on:
  pull_request:
    paths:
      - 'docker/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          file: "{{defaultContext}}:/docker/Dockerfile"
          platforms: linux/amd64,linux/arm64
          tags: testimage
          cache-from: type=gha
          cache-to: type=gha,mode=max